version: '3.8'
services:
  api:
    container_name: api
    build: 
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend
    depends_on:
      - database

  database:
    container_name: database
    build: 
      dockerfile: Dockerfile.database
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - database:/var/lib/postgresql/data
      - log:/var/lib/postgresql/log
    networks:
      - backend

volumes:
  database:
  log:

networks:
  backend:
    driver: bridge