version: '3.8'
services:
  api:
    image: gsidnick/nodejs2024q1-service-api:latest
    container_name: api
    build: 
      dockerfile: Dockerfile
      context: .
      target: development
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend
    depends_on:
      - database
    command: npm run start:docker

  database:
    image: gsidnick/nodejs2024q1-service-database:latest
    container_name: database
    build: 
      dockerfile: Dockerfile.database
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_EXT_PORT}:${POSTGRES_INT_PORT}
    volumes:
      - data:/var/lib/postgresql/data
      - logs:/logs
    networks:
      - backend
    command: postgres -c port=${POSTGRES_INT_PORT} -c logging_collector=on -c log_destination=stderr -c log_directory=/logs -c log_statement=all

volumes:
  data:
  logs:

networks:
  backend:
    driver: bridge